languageCode = "es"
languageName = "Español"
weight = 6
title = "Guía del coleccionista"

[params]
  displayName = "Español"
  isoCode = "es"
  rtl = false
  dateFormat = "2 de January de 2006"
  logo = "img/circular_rabbit.png"
  description = "Guía coleccionismo YuGiOh!."

[params.author]
  name = "Guía del coleccionista"
  image = "img/circular_rabbit.png"
  headline = "Guía coleccionismo YuGiOh!."
  bio = "Guía coleccionismo YuGiOh!."
  links = [
    { x-twitter = "https://twitter.com/Rescue_Rabbit00" },
  ]
