# -- Menú Principal --
# El menú principal se muestra en el encabezado en la parte superior de la página.

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Shortcodes"
  pageRef = "docs/shortcodes"
  weight = 15

[[main]]
  name = "Ejemplos"
  weight = 20

[[main]]
  name = "Muestras"
  parent = "Ejemplos"
  pageRef = "samples"
  weight = 16

[[main]]
  name = "Galería"
  parent = "Ejemplos"
  pageRef = "examples"
  weight = 30

[[main]]
  name = "Recetas"
  parent = "Ejemplos"
  pageRef = "guides"
  weight = 40

[[main]]
  name = "Usuarios"
  pageRef = "users"
  weight = 90

[[main]]
  name = "Merch"
  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
  weight = 100

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/Rescue_Rabbit00"
  weight = 200


# -- Menú de Pie de Página --

 [[footer]]
   name = "Autor"
   pageRef = "authors"
   weight = 20
