# -- Menú Principal --
# El menú principal se muestra en el encabezado en la parte superior de la página.

[[main]]
  name = "Inicio"
  pageRef = ""
  weight = 1

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Sobre el blog"
  pageRef = "sobre-el-blog"
  weight = 20

[[main]]
  name = "Autor"
  pageRef = "authors/rescuerabbit"
  weight = 30

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://twitter.com/Rescue_Rabbit00"
  weight = 200

# -- Menú de Pie de Página --

[[footer]]
  name = "Autor"
  pageRef = "authors/rescuerabbit"
  weight = 20